### ISSUE TITLE
Kickstrap 2.4/ inserting Next Post, Previous Post button

### ISSUE THREAD

**Issue by ganar** [adamjgrant/kickstart#178]
Is there a way to insert a _Previous/Next_ button in a post template? I want to be able to navigate between content pages but don't know how to code it. I Know that Jekill has an object to do that and wonder if Kickstrap 2.4 —or roots— has it too.

Thanks a lt for any help on the subject

**Comment by adamjgrant** [comment]
http://getkickstart.com/docs/3.x/ui/navigation/#pagination
