### ISSUE TITLE
Kickstart with Codekit

### ISSUE THREAD

**Issue by inseldesign** [adamjgrant/kickstart#186]
Hi,

just tried to get kickstart working with codekit but wasn't successful. I got "Error: Invalid CSS after "()": expected expression (e.g. 1px, bold), was ";" when i started to play around with the code snippets out of your docs. Even with libsass compiler it is not working. Maybe you have an idea otherwise i will give it a try with gulp. Thanks in advance.

Sascha

**Comment by adamjgrant** [comment]
Sorry, I don't currently test with or support code kit.
