### ISSUE TITLE
IcoMoon and FontAwesome to Cause CSS Conflicts

### ISSUE THREAD

**Issue by srsgores** [adamjgrant/kickstart#38]
The CSS files for both IcoMoon and FontAwesome both use the following CSS:

``` CSS
[class^="icon-"]::before, [class*=" icon-"]::before {
    /*css here*/
}
```

We should consider modifying the selector for one of the packages so that both can work together.

**Comment by paulovsky** [comment]
change your CSS into:

`i { font-family: 'FontAwesome', 'icomoon_font'  !important;}`

if you still find any conflicts, that's because two glyphs use the same code in both fonts.
