### ISSUE TITLE
Chosen() does not automatically resize when its parent's size changes with JavaScript

### ISSUE THREAD

**Issue by jmuheim** [adamjgrant/kickstart#47]
Hey there :-)

I really like your Chosen() inputs, but we have a small problem. We have a navigation bar on the left of our website which can be toggled to be displayed or not using JavaScript. When it is hidden, the main content has a width of span12 (fluid), and if it is shown, it hasa width of span11. Within the content we have many form elements that have their own spanX widths, and they all change their width relatively to the parent's width (span12 or span11), but the Chosen() input doesn't. I think this is because it is rendered only when the document is loaded. So is there a way to make it change its width? E.g. by re-triggering the function which renders the element?

Thank you. Josh

**Comment by qualitystuff** [comment]
I want to increase or decrease the size of dropdown according to no. option selected . dropdown size is increasing vertically when i select something . I want this thing to be done horizontally . 
Any help???

**Comment by ajkochanowicz** [comment]
This is about chosen? You might want to post this in their github.
Le Fri, Jun 12, 2015 à 8:52 AM, qualitystuff <notifications@github.com> a
écrit :

> I want to increase or decrease the size of dropdown according to no.
> option selected . dropdown size is increasing vertically when i select
> something . I want this thing to be done horizontally .
> Any help???
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ajkochanowicz/kickstart/issues/47#issuecomment-111481379>
> .
>
-- 
Adam Grant
